apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 192.168.65.3
  ports:
  - name: https
    port: 6443
    protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubernetes
  namespace: default
  labels:
    kubernetes.io/service-name: kubernetes
addressType: IPv4
endpoints:
- addresses:
  - 192.168.65.3
  conditions:
    ready: true
ports:
- name: https
  port: 6443
  protocol: TCP
