server:
  port: 8084
  servlet:
    context-path: /finance

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

jwt:
  secret: ${JWT_SECRET:very-secret-key-that-should-be-at-least-thirty-two-characters-long}
  expiration: ${JWT_EXPIRATION_MS:36000000} # 10 hours
