server:
  port: 8084
  servlet:
    context-path: /finance

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

jwt:
  secret: ${JWT_SECRET:very-secret-key-that-should-be-at-least-sixty-four-characters-long-for-hs512-which-is-highly-recommended-by-standards}
  expiration: ${JWT_EXPIRATION_MS:36000000} # 10 hours
  issuer: ${JWT_ISSUER:https://auth.engineerious.com}
  audience: ${JWT_AUDIENCE:finance-portal} # channel-id
  scope: ${JWT_SCOPE:openid profile}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}

