{{- range $name, $config := .Values.services }}
{{- if ne $name "financeui" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $config.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        {{- if $.Values.images.registry }}
        image: "{{ $.Values.images.registry }}/{{ $name }}:{{ index $.Values.images.tags $name }}"
        {{- else }}
        image: "{{ $name }}:{{ index $.Values.images.tags $name }}"
        {{- end }}
        imagePullPolicy: {{ $.Values.images.pullPolicy }}
        ports:
        - containerPort: {{ $config.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $.Values.global.environment }}
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ $.Values.postgres.username }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ $.Values.postgres.password }}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        livenessProbe:
          httpGet:
            path: /finance/actuator/health/liveness
            port: {{ $config.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
{{- end }}
{{- end }}
